package pipline
import chisel3.iotesters.PeekPokeTester
class Execute_t(c:Execute) extends PeekPokeTester(c){
 //     poke(c.io.readdata1,0)
 //     poke(c.io.pc,0)
 //     poke(c.io.pc_4,4)
 //     poke(c.io.operand_a_sel,0)
 //     poke(c.io.readdata2,7)
 //     poke(c.io.imm_mux,7)
 //     poke(c.io.operand_b_sel,1)
 //     poke(c.io.InstructionMem,7341715)
 //     poke(c.io.aluop,1)
 //     step(1)
 //    expect(c.io.out,7)
 //    expect(c.io.InstructionMem_out_11_7_bits,13)
 step(1)
 step(1)
  step(1)
  step(1)
 step(1)
  step(1)
  step(1)
 step(1)
  step(1)
  step(1)
 step(1)
  step(1)
  step(1)

}